// R9 MainAppLayout extraction — flat prop bag; refine into grouped interfaces in a follow-up slice.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type MainAppLayoutProps = {
  acknowledgedElevationDefaults: any
  activateRightDockTab: any
  activeDiff: any
  activeProvider: any
  activeRightDockTab: any
  activeSidebarChatId: any
  activeThreadSearchIndex: any
  activeWorkspaceBoard: any
  activeWorkspaceBoardCards: any
  activeWorkspaceBoardId: any
  activeWorkspaceBoardWorkspace: any
  advancedFxIntensity: any
  agentMcpStatusByProvider: any
  agentStatusByProvider: any
  agenticServices: any
  agenticWorkspaceGrantCount: any
  agenticWorkspaceGrants: any
  appMainStyle: any
  appTranscriptRef: any
  appVersion: any
  appearance: any
  approvalMode: any
  approvalTimeouts: any
  auraProviderKey: any
  autoFollowRef: any
  autoResumeParentOnSubThreadCompletion: any
  autoUpdateEnabled: any
  beginManualMainTranscriptJump: any
  beginManualSideTranscriptJump: any
  canCreateSideChatFromCurrent: any
  canOpenWorkspacePopout: any
  chatByIdRef: any
  chatContextNotice: any
  chatContextTurns: any
  chatPopoutParentChat: any
  chatSplitRegionRef: any
  chatSplitStyle: any
  chats: any
  claudeAuthStatus: any
  claudeBinaryPath: any
  claudeLoginState: any
  claudeReasoningEffort: any
  closeRightDockPanel: any
  closeThreadSearch: any
  codexMcpStatus: any
  codexModels: any
  codexReasoningEffort: any
  codexSandboxFallback: any
  codexStatus: any
  codexThreads: any
  collaboratingChatIds: any
  composerCtx: any
  copiedId: any
  copy: any
  connectedCollaborationChatIds: any
  currentAgentMcpStatus: any
  currentAgentStatus: any
  currentBlackboardEntries: any
  currentChat: any
  currentChatHumanCollaborationShare: any
  currentChatIdRef: any
  currentChatMediaRefs: any
  currentGeminiWorktree: any
  currentGuestParticipant: any
  currentGuestParticipantChatId: any
  currentPinnedMessages: any
  currentPreviewMenuOpen: any
  currentPreviewTargets: any
  currentProvider: any
  currentProviderCapabilities: any
  currentProviderLabel: any
  currentProviderModelOptions: any
  currentRun: any
  currentWorkspace: any
  currentWorkspacePath: any
  cursorProviderAvailable: any
  customModel: any
  deleteMessageFromChat: any
  diff: any
  diffRefreshStatus: any
  diffView: any
  displayCurrency: any
  displayFileChangeSummaries: any
  dockChatPopoutWindow: any
  dockPresence: any
  dockTabDefs: any
  effectiveInspectorWidth: any
  effectiveIsThinking: any
  ensembleEnabledParticipantsForCurrent: any
  exportProductDiagnostics: any
  externalPathGrants: any
  fileChangeDisplayAdds: any
  fileChangeDisplayDels: any
  fileChangeShouldShowStats: any
  fileChangeSummaryText: any
  focusedPaneGhostEnabled: any
  focusedPaneLivingWorkspaceEnabled: any
  focusedPaneSkyEnabled: any
  geminiCheckpointingEnabled: any
  geminiMcpBridgeEnabled: any
  geminiMcpBridgeStatus: any
  geminiTerminalEndRef: any
  geminiTerminalInput: any
  geminiTerminalStatusLabel: any
  geminiVersion: any
  getDefaultModelForProvider: any
  grokProviderAvailable: any
  guestComposerProvider: any
  guestThinkingModelBadge: any
  guestThinkingOllamaBrand: any
  handleAddChatToWorkspaceBoard: any
  handleAddLocalServerToWorkspaceBoard: any
  handleAddPinnedMessageToWorkspaceBoard: any
  handleAddRunQueueJobToWorkspaceBoard: any
  handleAddWorkflowToWorkspaceBoard: any
  handleAddWorkspaceBoardCard: any
  handleAgentQuestionDismiss: any
  handleAgentQuestionSubmit: any
  handleArchiveHandoff: any
  handleArchiveWorkspaceBoard: any
  handleCancelAuditRun: any
  handleCancelRunLane: any
  handleCancelWorkflowExecution: any
  handleClearClaudeApiKey: any
  handleClearCodexUsageCredential: any
  handleClearKimiApiKey: any
  handleCopyCurrentHumanCollaborationInvite: any
  handleCopyMessage: any
  handleCreateHandoffFromLane: any
  handleCreateHumanCollaborationShare: any
  handleCreateWorkspaceBoard: any
  handleDeleteAllChatHistory: any
  handleDeleteChat: any
  handleDeleteMessage: any
  handleDeleteQueuedMessage: any
  handleDeleteWorkflow: any
  handleDeleteWorkspaceBoard: any
  handleDeleteWorkspaceBoardCard: any
  handleDismissAuditRun: any
  handleDismissAuditRunNotice: any
  handleDismissOnboardingHint: any
  handleDispatchHandoff: any
  handleDuplicateRunLane: any
  handleDuplicateWorkspaceBoard: any
  handleEditQueuedMessage: any
  handleEditWorkflowInterval: any
  handleEndCurrentLinkedMainChat: any
  handleEndSidePanelChat: any
  handleForkCodexThread: any
  handleGeminiTerminalSubmit: any
  handleImportCodexUsageCredential: any
  handleJumpToLatest: any
  handleManualUsageRefresh: any
  handleMessageSelectionCandidate: any
  handleNavigateToWorkspace: any
  handleNewChat: any
  handleNewEnsemble: any
  handleNewGlobalChat: any
  handleOpenChangelogSheet: any
  handleOpenCockpitThread: any
  handleOpenInMultiview: any
  handleOpenLinkedChatInSidePanelById: any
  handleOpenLinkedChatInSidePanelFromSidebar: any
  handleOpenPinnedMessageFromSettings: any
  handleOpenSideChatFromLatestRunResult: any
  handleOpenSideChatFromMessage: any
  handleOpenSideChatFromRunResult: any
  handleOpenSideChatFromSelectedMessage: any
  handleOpenSideChatFromSummary: any
  handleOpenWorkflowCompose: any
  handleOpenWorkspaceBoard: any
  handlePersistRunAnalysis: any
  handlePlanChoiceSubmit: any
  handlePromoteCollaboratorComment: any
  handleProposedPlanApprove: any
  handleProposedPlanCustom: any
  handleProposedPlanDismiss: any
  handleRemoveAgenticWorkspaceGrant: any
  handleRemoveWorkspace: any
  handleRenameChat: any
  handleRenameWorkspaceBoard: any
  handleReorderQueuedMessages: any
  handleResumeCodexThread: any
  handleRetryRunLane: any
  handleReturnToSideChatParent: any
  handleRevokeHumanShare: any
  handleRightPanelResizeKeyDown: any
  handleRollbackCodexThread: any
  handleRunWorkflowNow: any
  handleSelectChat: any
  handleSelectSideChatTypeOption: any
  handleSelectWorkspace: any
  handleSetSideAgenticWorkspaceGrant: any
  handleSetWorkflowUnattended: any
  handleSettingsChange: any
  handleSideCancel: any
  handleSideModelChange: any
  handleSideProviderChange: any
  handleSideReasoningChange: any
  handleSideRun: any
  handleSideToggleFastMode: any
  handleSidebarQuickUpdate: any
  handleStartSharedChat: any
  handleSteerToQueuedMessage: any
  handleStopHumanCollaborationSharing: any
  handleStoreClaudeApiKey: any
  handleStoreKimiApiKey: any
  handleToggleArchiveChat: any
  handleTogglePinChat: any
  handleTogglePinWorkspace: any
  handleTogglePinWorkspaceBoard: any
  handleToggleWorkflowEnabled: any
  handleTriggerClaudeLogin: any
  handleUpdateWorkspaceBoardCard: any
  handleUpgradeProviderCli: any
  handleWorkspaceSidebarResizeKeyDown: any
  handoffCards: any
  hasCurrentHandoffDraft: any
  hasWorkspaceContext: any
  hideSideChatPane: any
  hostWeather: any
  humanCollaborationShares: any
  inspectingRunId: any
  installGeminiMcpBridge: any
  interfaceStyle: any
  isAdvancedFxActive: any
  isChatExpanded: any
  isChatMediaPanelOpen: any
  isChatPopoutWindow: any
  isCurrentEnsembleChat: any
  isCurrentGlobalChat: any
  isCurrentGuestParticipantRunning: any
  isEnsembleModeEnabled: any
  isFxEnabled: any
  isLinkedChatPopout: any
  isMultiviewSplit: any
  isOldVersion: any
  isPinnedMessagesPanelOpen: any
  isSideChatProviderLocked: any
  isSideChatRunning: any
  isSideComposerLocked: any
  isSideEnsembleComposerLocked: any
  isSideSplitOpen: any
  isTerminalDockAvailable: any
  isThinking: any
  isWelcomeChat: any
  jumpToTranscriptMessage: any
  kimiAuthStatus: any
  kimiBinaryPath: any
  kimiThinkingEnabled: any
  latestSideChatRunResultSeed: any
  logsEndRef: any
  manualUsageRefreshInFlight: any
  multiview: any
  ollamaBaseUrl: any
  ollamaDefaultModel: any
  ollamaDefaultRunProfile: any
  ollamaRunProfiles: any
  ollamaToolControlTier: any
  openChatPopoutWindow: any
  openCurrentSideChatPresentation: any
  openFileChangeInWorkbench: any
  openLinkedChatAsMain: any
  openMediaPane: any
  openWorkspacePopoutWindow: any
  overestimatePercent: any
  pendingAgentApproval: any
  pendingAgentApprovalByChatId: any
  pendingAgentQuestions: any
  pendingAgentQuestionsByChatId: any
  pendingApprovalQueueByChatId: any
  pendingPlanChoice: any
  pendingProposedPlan: any
  pendingQueuedAppRunIds: any
  popOutLinkedChat: any
  popoutMenuOpen: any
  popoutMenuRef: any
  previewChatMediaRef: any
  productOperationsStatus: any
  prompt: any
  providerCapabilitiesByProvider: any
  providerCliUpgradeState: any
  providerRates: any
  providerShellClass: any
  queuedRunQueueCount: any
  queuedRunStatusByAppRunId: any
  rawFilter: any
  rawLogs: any
  rawLogsEndRef: any
  refractionEnabled: any
  refreshCodexThreads: any
  refreshDiff: any
  refreshGeminiMcpBridgeStatus: any
  refreshProductOperationsStatus: any
  refreshProviderMetadata: any
  rememberSideChatComposerSelection: any
  renderMultiviewPaneCell: any
  renderPreviewLaunchError: any
  renderPreviewTargetMenu: any
  repairProductInstall: any
  rightDockStyle: any
  rightDockVisible: any
  rightTab: any
  runCompleteDurationText: any
  runCompleteNotice: any
  runDiff: any
  runFxStatus: any
  runLanes: any
  runPreviewTargetAction: any
  runQueueJobs: any
  runningChatIds: any
  runningChatIdsArray: any
  scheduledTasks: any
  selectThreadSearchMatch: any
  selectedModelType: any
  selectedParticipant: any
  selectedSideChatSeedMessage: any
  selectedSideChatTypeOption: any
  sessionTrust: any
  setChatMediaPanelOpenPreservingTranscript: any
  setChatPromptDraft: any
  setDiffView: any
  setGeminiTerminalInput: any
  setInspectingRunId: any
  setIsPinnedMessagesPanelOpen: any
  setJoinSharedChatOpen: any
  setPendingElevation: any
  setPopoutMenuOpen: any
  setPreviewChatMediaRef: any
  setPreviewMenuTarget: any
  setRawFilter: any
  setRawLogs: any
  setRightDockTab: any
  setRightTab: any
  setSessionTrust: any
  setSettingsActiveTab: any
  setShowBugReportSheet: any
  setShowCockpit: any
  setShowFileEditor: any
  setShowFirstLaunchSheet: any
  setShowGeminiTerminal: any
  setShowGhostCompanion: any
  setShowSettings: any
  setShowSkyVisualFx: any
  setShowTerminal: any
  setShowWorkspaceSidebar: any
  setSideChatMenuOpen: any
  setSubThreadCreatorParent: any
  setThreadRawLogs: any
  setThreadSearchActiveIndex: any
  setThreadSearchQuery: any
  setWelcomeUsageTab: any
  settings: any
  settingsActiveTab: any
  settingsPinnedMessageGroups: any
  shouldShowWelcomeUsageDashboard: any
  showAgentAuraFx: any
  showBugReportSheet: any
  showChangelogSheet: any
  showCockpit: any
  showFileEditor: any
  showFirstLaunchSheet: any
  showGeminiTerminal: any
  showJumpToLatestPill: any
  showOnboardingHint: any
  showRunDataVizFx: any
  showSettings: any
  showTerminal: any
  showWorkspaceSidebar: any
  sideAutoFollowRef: any
  sideCanRun: any
  sideChat: any
  sideChatIsWelcome: any
  sideChatMenuOpen: any
  sideChatMenuRef: any
  sideChatSeedMessageId: any
  sideChatStatusLabel: any
  sideChatSummarySeed: any
  sideChatTokenTally: any
  sideChatTypePickerOptions: any
  sideChatWelcomeThreadLabel: any
  sideChatWelcomeWorkspaceLabel: any
  sideClaudeReasoning: any
  sideCodexReasoning: any
  sideComposerContextMenu: any
  sideComposerHasMention: any
  sideComposerModelOptions: any
  sideComposerProvider: any
  sideComposerReasoningOptions: any
  sideComposerRunTimecodeStartedAt: any
  sideComposerSelectedModel: any
  sideComposerSelectedReasoning: any
  sideComposerSelection: any
  sideComposerTextareaRef: any
  sideContextModelId: any
  sideCumulativeRunBaseMs: any
  sideDualComposerTelemetry: any
  sideEnabledGrantIds: any
  sideFastModeCapableModelIds: any
  sideFastModeEnabled: any
  sideGrantServices: any
  sideKimiThinking: any
  sideLiveRunOutputTokens: any
  sideLogsEndRef: any
  sidePanelAgentIdentity: any
  sidePanelKindLabel: any
  sidePanelLayoutClass: any
  sidePanelParentChat: any
  sidePanelRelation: any
  sidePermissionOptions: any
  sidePrompt: any
  sideProvider: any
  sideQueuedMessagesAboveRowEntries: any
  sideRun: any
  sideRunCompleteNotice: any
  sideSelectedPermission: any
  sideThinkingModelBadge: any
  sideThinkingProvider: any
  sideThinkingProviderClass: any
  sideThinkingProviderLabel: any
  sideThreadTokenTallyHasValue: any
  sideTranscriptContentRef: any
  sideTranscriptScrollRef: any
  sideWorkspace: any
  sidebarPresence: any
  sidebarSearchFocusRequestId: any
  startRightPanelResize: any
  startWorkspaceSidebarResize: any
  thinkingModelBadge: any
  thinkingProvider: any
  thinkingProviderClass: any
  thinkingProviderLabel: any
  threadSearchFocusRequestId: any
  threadSearchMatches: any
  threadSearchQuery: any
  threadSearchShortcutHint: any
  threadSearchVisible: any
  togglePinMessageInChat: any
  transcriptContentRef: any
  transcriptJumpRequest: any
  transcriptMessages: any
  transcriptScrollRef: any
  transcriptStyle: any
  trustResult: any
  unreadFromBottomCount: any
  updateChannel: any
  updatePinnedNotesForChat: any
  updateStatus: any
  usageInitialized: any
  usageRecords: any
  usageRefreshTick: any
  usageSummary: any
  visibleAuditRun: any
  visibleAuditRunNotice: any
  visibleGeminiTerminalLogs: any
  visibleRunCompleteNotice: any
  welcomeDashboardCardEnabled: any
  welcomeDashboardHiddenByFit: any
  welcomeDashboardRegionRef: any
  welcomeUsageDashboardData: any
  welcomeUsageTab: any
  workflowDefinitions: any
  workspaceAddPointerActive: any
  workspaceBoardApiReady: any
  workspaceBoardCards: any
  workspaceBoards: any
  workspaceSearchShortcutHint: any
  workspaceSidebarWidth: any
  workspaces: any
}
