/**
 * Channels a chat, editor, workbench, diff, or other secondary renderer may
 * invoke. Owner-scoped chat/workspace channels still enforce their narrower
 * authority in their domain handlers; membership here only lets the request
 * reach that handler.
 *
 * This list deliberately freezes the previously supported secondary-renderer
 * surface. New or misspelled channels fail closed in
 * `ipcChannelRequiresMainRenderer` until they are reviewed and added here.
 */
export const SECONDARY_RENDERER_SAFE_IPC_CHANNELS = new Set<string>([
  'add-or-update-workspace',
  'agentic-yolo-get',
  'agentic-yolo-set',
  'answer-agent-question',
  'answer-ensemble-poll',
  'app-shell-stats:snapshot',
  'audit-run:cancel',
  'audit-run:start',
  'blackboard-queued-ensemble-prompt',
  'cancel-agent-question',
  'cancel-agent-run',
  'cancel-scheduled-task',
  'cancel-ensemble-participant-wakeup',
  'cancel-ensemble-round',
  'cancel-gemini',
  'capture-snapshot',
  'changelog-snapshot',
  'check-trust',
  'clear-chats',
  'clear-blackboard-entries',
  'clear-workspaces',
  'closeout:summarize',
  'continuation:propose',
  'compact-provider-context',
  'compose-run',
  'composer-audio:transcribe',
  'copy-chat-messages',
  'compute-run-diff',
  'copy-chat-markdown-transcript',
  'create-chat',
  'create-ensemble-chat',
  'create-github-pr',
  'create-global-chat',
  'create-side-chat',
  'create-sub-thread',
  'delete-blackboard-entry',
  'delete-chat',
  'delete-evidence-pack',
  'delete-scheduled-task',
  'delete-workflow-definition',
  'delete-workspace-board',
  'delete-workspace-board-card',
  'delete-workspace-file',
  'discover-gemini-commands',
  'discover-gemini-memory',
  'dock-side-chat-popout',
  'external-path:pick-and-persist',
  'external-path:repair-stale',
  'external-path:revoke',
  'fallback-promoted-steer-job',
  'favicon:getForUrl',
  'fork-agent-thread',
  'fork:get-capability',
  'fx-rates:get',
  'get-agent-mcp-status',
  'get-agent-models',
  'get-agent-rate-limits',
  'get-agent-stats-summaries',
  'get-agent-status',
  'get-app-version',
  'get-approval-ledger',
  'get-audit-run',
  'get-audit-runs',
  'get-capability-ledger-snapshot',
  'get-chat',
  'get-chat-list',
  'get-chats',
  'unarchive-chat',
  'export-archived-chat',
  'get-claude-auth-status',
  'get-codex-usage-snapshot',
  'get-diff',
  'get-evidence-packs',
  'get-external-usage',
  'get-file-icon',
  'get-gemini-auth-status',
  'get-gemini-capabilities',
  'get-gemini-version',
  'get-handoff-cards',
  'get-host-weather',
  'get-kimi-auth-status',
  'get-pinned-messages',
  'get-provider-adapters',
  'get-configured-provider-snapshot',
  'get-provider-capabilities',
  'get-repo-convention-indexes',
  'get-run-event-replay',
  'get-run-events',
  'get-run-queue-jobs',
  'get-run-recovery-records',
  'get-runtime-profiles',
  'get-scheduled-tasks',
  'get-settings',
  'get-side-chats',
  'get-sub-threads',
  'get-usage',
  'get-workflow-definitions',
  'get-workflow-run-events',
  'get-workflow-run-summaries',
  'get-workspace-activity',
  'get-workspace-board-cards',
  'get-workspace-boards',
  'get-workspace-change-sets',
  'get-workspaces',
  'fanout-candidates:diff',
  'fanout-candidates:discard',
  'fanout-candidates:list',
  'fanout-candidates:promote',
  'git:checkout-branch',
  'git:commit',
  'git:create-branch',
  'git:create-worktree',
  'git:invalidate-snapshot',
  'git:list-branches',
  'git:list-worktrees',
  'git:push',
  'git:remove-worktree',
  'git:select-worktree',
  'git:snapshot',
  'git:workspace-stats',
  'git:work-provenance',
  'git:stage',
  'git:subscribe-snapshot',
  'git:unstage',
  'git:unsubscribe-snapshot',
  'work-locks:list',
  'work-locks:subscribe',
  'work-locks:unsubscribe',
  'github:ci-status',
  'github:pr-readiness',
  'github:pr-status',
  'github:set-watched-pr',
  'github:watch-pr-notify-ack',
  'grok-usage:probe',
  // Every renderer mounts the Host projection provider. These two read-only
  // channels keep popouts coherent; governed mutations remain main-only.
  'host-projection:snapshot',
  'host-projection:deltas-since',
  'human-collaboration-collaborator:append-comment',
  'human-collaboration-collaborator:load-older',
  'human-collaboration-collaborator:confirm',
  'human-collaboration-collaborator:join',
  'human-collaboration-collaborator:last-session',
  'human-collaboration-collaborator:leave',
  'human-collaboration-collaborator:reconnect',
  'human-collaboration-runtime:append-comment',
  'human-collaboration-runtime:begin-admission',
  'human-collaboration-runtime:confirm-sas',
  'human-collaboration-runtime:disconnect',
  'human-collaboration-runtime:receive-frame',
  'human-collaboration-runtime:subscribe-projection',
  'human-collaboration:append-comment',
  'human-collaboration:approve-contribution',
  'human-collaboration:audit-log',
  'human-collaboration:connected-chat-ids',
  'human-collaboration:consume-invite',
  'human-collaboration:copy-invite',
  'human-collaboration:create-share',
  'human-collaboration:deny-contribution',
  'human-collaboration:invite-health',
  'human-collaboration:list-pending-contributions',
  'human-collaboration:list-shares',
  'human-collaboration:projection',
  'human-collaboration:promote-comment',
  'human-collaboration:revoke-participant',
  'human-collaboration:revoke-share',
  'human-collaboration:session-status',
  'human-collaboration:set-host-review',
  'human-collaboration:set-full-history',
  'human-collaboration:update-share-rules',
  'image-generation:get-status',
  'launch-attempts-snapshot',
  'launch-start',
  'launch-stop',
  'launch-targets-snapshot',
  'lease-promoted-steer-job',
  'lease-run-queue-job',
  'list-agent-threads',
  'list-gemini-auth-profiles',
  'list-gemini-sessions',
  'list-workspace-files',
  'list-workspace-files-for-editor',
  'media-asset:get-path',
  'media-asset:reveal',
  'media-asset:save-as',
  'media-asset:copy-image',
  'mistral-quota:get',
  'native-capabilities:snapshot',
  'open-workspace-popout',
  'plugins:get-activation',
  'post-blackboard-entry',
  'probe-external-path',
  'promote-queued-job-for-steer',
  'providerRates:get',
  'pty-resize',
  'pty-write',
  'read-image-preview',
  'read-workspace-file',
  'reap-abandoned-chats',
  'rebind-chat-workspace',
  'record-approval-elevation-ack',
  'record-product-crash',
  'record-usage',
  'remove-agentic-workspace-grant',
  'remove-queued-ensemble-prompt',
  'remove-workspace',
  'request-ensemble-participant-seat-change',
  'request-ensemble-user-roster-mutation',
  'request-run-queue-job',
  'resize-gemini-session',
  'respond-agent-approval',
  'rollback-agent-thread',
  'run-agent',
  'run-analyst:analyze',
  'run-approved-host-command',
  'run-ensemble-round',
  'run-gemini',
  'run-workflow-now',
  'save-chat',
  'save-clipboard-image-attachment',
  'set-chat-git-workflow',
  'save-evidence-pack',
  'save-repo-convention-index',
  'save-scheduled-task',
  'save-workflow-definition',
  'save-workspace-board',
  'save-workspace-board-card',
  'select-external-path-grant',
  'select-image-files',
  'select-workspace',
  'session-checkpoints:accept',
  'session-checkpoints:dismiss',
  'session-checkpoints:latest',
  'set-appearance-mode',
  'set-chat-kind',
  'set-workflow-unattended-elevation',
  'shell:open-link',
  'shell:reveal-in-finder',
  'sidebar:copy-chat-transcript-path',
  'sidebar:copy-chat-working-directory',
  'sidebar:copy-workspace-directory',
  'sidebar:show-chat-workspace-in-finder',
  'sidebar:show-workspace-in-finder',
  'skip-ensemble-participant',
  'skip-ensemble-read-fanout',
  'skip-ensemble-fanout-lane',
  'spellcheck:add-word-to-dictionary',
  'spellcheck:get-last-context',
  'spellcheck:replace-misspelling',
  'start-agent-review',
  'start-gemini-session',
  'start-pty',
  'steer-queued-ensemble-prompt',
  'stop-gemini-session',
  'stop-pty',
  'transition-run-queue-job',
  'truncate-chat',
  'trust-workspace',
  'trusted-session-get',
  'trusted-session-set',
  'update-scheduled-task',
  'update-snapshot',
  'update-workflow-definition',
  'update-workspace-board',
  'update-workspace-board-card',
  'upsert-agentic-workspace-grant',
  'wake-ensemble-participant-now',
  'write-gemini-input',
  'write-gemini-session',
  'write-workspace-file'
])

/**
 * Explicit inventory of the currently registered channels that always require
 * the main renderer. Runtime authority does not depend on this list: anything
 * absent from the secondary-safe allowlist also requires main. Keeping the
 * inventory lets tests force a conscious classification whenever the IPC
 * catalogue changes.
 */
export const MAIN_RENDERER_ONLY_IPC_CHANNELS = new Set<string>([
  // Host commands and receipt correlation are currently presented only by
  // the primary app surface. Read-only projection continuity is safe above.
  'host-projection:command-submit',
  'host-projection:receipt-lookup',
  // The Gemini API key is main-renderer-only; workspace popouts and utility
  // renderers must never be able to submit or clear credential material.
  'antigravity-gemini-api:get-secret-status',
  'antigravity-gemini-api:set-secret',
  'antigravity-gemini-api:clear-secret',
  // The discovery outcome describes that same credential's health, so it stays
  // on the identical main-renderer-only footing even though it carries no key.
  'antigravity-gemini-api:get-discovery-outcome',
  // About can open only build-generated, fixed resource paths. Utility/chat
  // renderers have no reason to launch host applications for legal notices.
  'licenses:get-status',
  'licenses:open-notice',
  'pi:get-key-status',
  'pi:set-upstream-key',
  'pi:clear-upstream-key',
  'pi:clear-all-keys',
  // This hook is credential-free, but it projects machine-wide quota and
  // billing readings from another local app. Only the primary Model Usage
  // surface may request that account-level telemetry.
  'quota-snapshot-hook:get',

  // Declaring the Mistral plan and anchoring the quota meter to a console
  // reading are Settings-level acts that rewrite how every seat's burn is
  // banded. Reading the meter (`mistral-quota:get`) stays secondary-safe;
  // rewriting its basis does not.
  'mistral-quota:set-plan',
  'mistral-quota:set-anchor',
  'mistral-quota:clear-anchor',
  // The Admin API key is credential material, so it sits on the identical
  // main-renderer-only footing as the Gemini and Pi keys above. The refresh it
  // authorises joins it: a popout must not be able to spend an org's admin key.
  'mistral-admin-key:status',
  'mistral-admin-key:set',
  'mistral-admin-key:clear',
  'mistral-quota:refresh-admin',

  // Canvas WebContentsView state belongs to the primary window. Popouts and
  // other secondary renderers must not create or reposition an overlay over it.
  'canvas:open-window',
  'canvas:open-embedded',
  'canvas:open-sketch-window',
  'canvas:open-sketch-embedded',
  'canvas:adopt-embedded',
  'canvas:set-bounds',
  'canvas:set-visible',
  'canvas:close',
  'canvas:close-chat',
  'canvas:clear-browser-profile',
  'canvas:navigate-chat',
  'canvas:list',
  'canvas:list-chat',

  // Mesh Canvas's private asset URLs and human file picker are rendered only
  // in the main chat window; secondary renderers have no independent surface.
  'mesh-scene:list-chat',
  'mesh-scene:view',
  'mesh-scene:import-user-model',
  'mesh-scene:import-user-package',
  'mesh-scene:close-presentation',
  'mesh-scene:delete',

  // Simulator Canvas dock lives in the main chat window only; secondary
  // renderers have no independent bezel surface for host simctl actions.
  'simulator-canvas:status',
  'simulator-canvas:claim-control',
  'simulator-canvas:release-control',
  'simulator-canvas:session',
  'simulator-canvas:open-app',
  'simulator-canvas:list-devices',
  'simulator-canvas:boot',
  'simulator-canvas:pick-app',
  'simulator-canvas:install',
  'simulator-canvas:launch',
  'simulator-canvas:terminate',
  'simulator-canvas:screenshot',
  'simulator-canvas:interaction-status',
  'simulator-canvas:tap',
  'simulator-canvas:type',
  'simulator-canvas:scroll',
  'simulator-canvas:inspect',
  'simulator-canvas:button',
  'simulator-canvas:rotate',
  // Simulator control can install a local companion, so only the primary
  // settings/canvas renderer may request its status or begin setup.
  'simulator-control:setup-status',
  'simulator-control:setup',
  'simulator-canvas:claim-control',
  'simulator-canvas:pick-app',
  'simulator-canvas:session',

  // Office suite documents live in the main window's right dock only; there
  // is no office popout surface, so secondary renderers have no claim on
  // these channels. The handlers additionally assert workspace-file scope.
  'office:read-document',
  'office:write-document',
  'office:delete-document',
  'office:read-external-document',
  'office:write-external-document',
  'office:import-document',
  'office:reveal-document',
  'office:open-document-in-default-app',

  // Microsoft account credentials are managed from the main window only,
  // matching every other secret-bearing surface.
  'outlook:status',
  'outlook:start-sign-in',
  'outlook:poll-sign-in',
  'outlook:disconnect',

  // Project registry (Work surface): app-level organisational state managed
  // from the main window only; the domain handler asserts the same authority.
  'projects:snapshot',
  'projects:apply-op',
  'projects:set-home-chat',
  'projects:update-work-profile',
  'projects:reference-op',
  'projects:graph-edge-op',
  'projects:verify-reference',
  'projects:pick-reference-path',
  'projects:import-legacy',
  'projects:list-reference-proposals',
  'projects:review-reference-proposal',
  'projects:studio-generate',
  'projects:studio-save',
  'projects:studio-discard',
  'projects:studio-list',
  'projects:extract-reference',
  'projects:get-reference-extract',
  'projects:revoke-reference-extract',
  'projects:read-reference-extract-text',

  // Execution graphs are app-level orchestration state. Their domain handlers
  // repeat this assertion and resolve all workspace/chat authority in main.
  'execution-graphs:diagnostics',
  'execution-graphs:list',
  'execution-graphs:get',
  'execution-graphs:get-layout',
  'execution-graphs:save-layout',
  'execution-runs:list',
  'execution-runs:get',
  'execution-runs:events',
  'execution-runs:append-stack-step',
  'execution-runs:cancel',
  'execution-runs:cancel-step',
  'execution-runs:formalize',

  // Global settings, runtime profiles, encrypted secrets, and handoff records.
  'update-settings',
  'prompt-cache:get-policy',
  'prompt-cache:get-capabilities',
  'prompt-cache:get-diagnostics',
  'prompt-cache:save-policy',
  'set-bridge-daemon-enabled',
  'save-runtime-profile',
  'delete-runtime-profile',
  'get-extension-secret-status',
  'set-extension-secret',
  'clear-extension-secret',
  'get-managed-policy-status',
  'save-handoff-card',
  'update-handoff-card',
  'delete-handoff-card',

  // Plugin inventory, installation, and secret material.
  'plugins:get-catalog',
  'plugins:get-contributions',
  'plugins:get-secret-status',
  'plugins:set-secret',
  'plugins:clear-secret',
  'plugins:materialize-mcp-preset',
  'plugins:install',
  'plugins:set-enabled',
  'plugins:update',
  'plugins:uninstall',

  // Skills Settings + progressive skill discovery store.
  'skills:list-effective',
  'skills:list-user',
  'skills:list-workspace',
  'skills:upsert',
  'skills:delete',
  'skills:set-enabled',
  'skills:reveal-root',

  // Host shell hooks Settings + effective merge.
  'hooks:get-effective',
  'hooks:get-user',
  'hooks:get-workspace',
  'hooks:upsert',
  'hooks:delete',
  'hooks:set-enabled',
  'hooks:reveal-root',

  // Provider credentials, login processes, and host-wide provider bridges.
  'store-claude-api-key',
  'clear-claude-api-key',
  'trigger-claude-login',
  'store-kimi-api-key',
  'clear-kimi-api-key',
  'save-gemini-auth-profile',
  'delete-gemini-auth-profile',
  'set-default-gemini-auth-profile',
  'start-gemini-oauth-login',
  'get-gemini-oauth-login-status',
  'cancel-gemini-oauth-login',
  'provider:open-login-terminal',
  'provider:open-logout-terminal',
  'provider:open-upgrade-terminal',
  'provider:open-kimi-upgrade-terminal',
  'host-tool:open-install-terminal',
  'host-tool:status',
  'install-command:open-terminal',
  'get-gemini-mcp-bridge-status',
  'install-gemini-mcp-bridge',
  'set-gemini-mcp-bridge-enabled',
  'import-codex-usage-credential',
  'clear-codex-usage-credential',

  // Mobile bridge, remote allowlist, pairing, and notification credentials.
  'bridge-allowlist-upsert',
  'bridge-allowlist-remove',
  'bridge-allowlist-clear',
  'bridge-begin-pairing',
  'bridge-finalize-pairing',
  'bridge-unpair-device',
  'ios-remote-tailscale-enable',
  'ios-remote-tailscale-test',
  'ios-remote-tailscale-disable',
  'ios-remote-tailscale-link',
  'ios-remote-tailscale-oauth-set',
  'ios-remote-tailscale-oauth-clear',
  'ios-remote-tailscale-status',
  'ios-remote-tailscale-oauth-status',
  'get-ios-remote-config',
  'set-ios-remote-config',
  'bridge-list-paired-devices',
  'bridge-networking-status',
  'bridge-allowlist-list',
  'select-apns-key-file',
  'get-apns-config',
  'set-apns-config',
  'clear-apns-config',
  'test-apns-push',

  // Host-wide generation credentials and capability toggles.
  'image-generation:set-enabled',
  'image-generation:set-key',
  'image-generation:clear-key',

  // Product update/install, diagnostics retention, and local process control.
  'check-for-updates',
  'download-update',
  'download-update-and-restart',
  'install-update-on-quit',
  'install-update-now',
  'mark-changelog-seen',
  'export-product-diagnostics',
  'export-product-audit-bundle',
  'verify-product-audit-bundle',
  'purge-product-audit-retention',
  'repair-product-install',
  'get-product-operations-status',
  'get-product-crashes',
  'submit-bug-report',
  'local-servers-snapshot',
  'local-servers-refresh',
  'local-servers-stop',
  'local-servers-stop-all',

  // Memory-promotion review/apply and its schedule are Settings-only surfaces.
  'update-memory-proposal',
  'apply-memory-proposal',
  'run-manual-introspection',
  'update-introspection-schedule',
  'get-memory-proposal-packs',
  'get-memory-proposal-pack',
  'get-introspection-schedule',

  // Host-wide integrations and confidential channel history are Settings-only.
  'discord-context:list-targets',
  'discord-context:read-channel',
  'fx-rates:refresh',
  'providerRates:probe',

  // Global app/roster state and user-authorized desktop capture/attachment gates.
  'ensemble-roster-presets:sync',
  'ensemble:apply-roster-preset',
  'ensemble:update-live-round-config',
  'attach-window:pick',
  'attach-window:detach',
  'attach-window:control-session',
  'attach-window:status',
  'sticky-appwatch:get',
  'sticky-appwatch:stash',
  'sticky-appwatch:clear',
  'app:quit',

  // Peer thread-to-thread messages (S8). These were already main-renderer-only
  // via the fail-closed default below — listing them changes no behaviour, it
  // records the decision the classification test exists to force. Main-renderer
  // authority is load-bearing for `thread-message:send` in particular: a send
  // arriving on this channel is recorded as USER-AUTHORED, and a user-composed
  // message skips the approval prompt. Widening any of these to a secondary
  // renderer would widen a path that bypasses approval, so they stay here.
  'thread-message:targets',
  'thread-message:inbox',
  'thread-message:send',

  // Force-releasing a recovery-blocked acquisition is a native-confirmed,
  // host-wide recovery act. Projection reads stay secondary-safe; this does not.
  'work-locks:force-release-recovery'
])

export function ipcChannelRequiresMainRenderer(channel: string): boolean {
  return (
    MAIN_RENDERER_ONLY_IPC_CHANNELS.has(channel) ||
    !SECONDARY_RENDERER_SAFE_IPC_CHANNELS.has(channel)
  )
}
