/**
 * Desktop terminal-window handoff for a detached pure-Node Host.
 *
 * The TUI starts its Host with stdio ignored so the Host can outlive the TUI.
 * Provider login therefore cannot inherit that process's terminal. This module
 * adapts the existing exact-argv HostNodeTerminalLauncher to a new OS terminal
 * window without widening the provider command catalogue or persisting env
 * values. Provider CLIs remain responsible for browser/device-code auth.
 */

import { constants, accessSync, chmodSync, lstatSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { delimiter, join, resolve } from 'node:path'
import { randomUUID } from 'node:crypto'
import { spawn as nodeSpawn, type ChildProcess, type SpawnOptions } from 'node:child_process'

import {
  createHostNodeTerminalLauncher,
  type HostNodeTerminalLauncher
} from './HostNodeTerminalLauncher'

type HostNodeTerminalWindowSpawn = (
  executable: string,
  args: readonly string[],
  options: SpawnOptions
) => ChildProcess

export interface HostNodeTerminalWindowLauncherOptions {
  readonly platform?: NodeJS.Platform
  readonly env?: NodeJS.ProcessEnv
  readonly spawn?: HostNodeTerminalWindowSpawn
  readonly temporaryDirectory?: () => string
  readonly idFactory?: () => string
  readonly darwinOpenExecutable?: string
  readonly windowsPowerShellExecutable?: string
  readonly linuxTerminalExecutable?: string
  readonly pathExecutable?: (name: string, env: NodeJS.ProcessEnv) => string | null
}

interface LinuxTerminalCommand {
  readonly executable: string
  readonly args: (scriptPath: string) => readonly string[]
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function removedEnvironmentKeys(
  base: NodeJS.ProcessEnv,
  supplied: NodeJS.ProcessEnv | undefined
): string[] {
  if (!supplied) return []
  return Object.keys(base)
    .filter((key) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && supplied[key] === undefined)
    .sort()
}

function posixScript(
  executable: string,
  args: readonly string[],
  removedKeys: readonly string[]
): string {
  const command = [executable, ...args].map(shQuote).join(' ')
  return `${[
    '#!/bin/sh',
    '# Generated by TaskWraith for one exact provider sign-in handoff.',
    ...removedKeys.map((key) => `unset ${key}`),
    "printf '%s\\n' 'Signing in to a provider for TaskWraith…'",
    `printf '%s\\n\\n' ${shQuote(`> ${command}`)}`,
    command,
    'status=$?',
    'printf \'\\nSign-in command finished (exit %s).\\n\' "$status"',
    "printf '%s' 'Press Return to close this window.'",
    'IFS= read -r _taskwraith_close || true',
    'exit "$status"'
  ].join('\n')}\n`
}

function powershellScript(
  executable: string,
  args: readonly string[],
  removedKeys: readonly string[]
): string {
  const invocation = ['&', psQuote(executable), ...args.map(psQuote)].join(' ')
  return `${[
    '# Generated by TaskWraith for one exact provider sign-in handoff.',
    "$ErrorActionPreference = 'Continue'",
    ...removedKeys.map(
      (key) => `Remove-Item ${psQuote(`Env:${key}`)} -ErrorAction SilentlyContinue`
    ),
    "Write-Host 'Signing in to a provider for TaskWraith…'",
    `Write-Host ${psQuote(`> ${[executable, ...args].join(' ')}`)}`,
    "Write-Host ''",
    invocation,
    '$status = if ($LASTEXITCODE -ne $null) { $LASTEXITCODE } else { 0 }',
    "Write-Host ''",
    "Write-Host ('Sign-in command finished (exit ' + $status + ').')",
    "Read-Host 'Press Return to close this window' | Out-Null",
    'exit $status'
  ].join('\r\n')}\r\n`
}

function defaultPathExecutable(name: string, env: NodeJS.ProcessEnv): string | null {
  for (const directory of String(env.PATH || '').split(delimiter)) {
    if (!directory) continue
    const candidate = resolve(directory, name)
    try {
      accessSync(candidate, constants.X_OK)
      return candidate
    } catch {
      // Try the next PATH entry.
    }
  }
  return null
}

function linuxTerminalCommand(
  options: HostNodeTerminalWindowLauncherOptions,
  env: NodeJS.ProcessEnv
): LinuxTerminalCommand | null {
  if (!String(env.DISPLAY || '').trim() && !String(env.WAYLAND_DISPLAY || '').trim()) return null
  const resolveExecutable = options.pathExecutable ?? defaultPathExecutable
  const explicit = options.linuxTerminalExecutable
  const candidates = explicit
    ? [explicit]
    : ['x-terminal-emulator', 'gnome-terminal', 'konsole', 'xterm']
  for (const name of candidates) {
    const executable = explicit ? name : resolveExecutable(name, env)
    if (!executable) continue
    const base = executable.split('/').at(-1)?.toLowerCase()
    return {
      executable,
      args:
        base === 'gnome-terminal'
          ? (scriptPath) => ['--', scriptPath]
          : (scriptPath) => ['-e', scriptPath]
    }
  }
  return null
}

function scriptDirectory(options: HostNodeTerminalWindowLauncherOptions): string {
  const directory = (
    options.temporaryDirectory ?? (() => mkdtempSync(join(tmpdir(), 'taskwraith-provider-login-')))
  )()
  const stat = lstatSync(directory)
  if (!stat.isDirectory() || stat.isSymbolicLink()) {
    throw new Error('Provider terminal handoff directory is unsafe.')
  }
  return directory
}

function scriptId(options: HostNodeTerminalWindowLauncherOptions): string {
  const value = (options.idFactory ?? randomUUID)()
  if (!/^[A-Za-z0-9-]{1,80}$/.test(value)) {
    throw new Error('Provider terminal handoff id is invalid.')
  }
  return value
}

function writeScript(
  options: HostNodeTerminalWindowLauncherOptions,
  extension: 'command' | 'sh' | 'ps1',
  content: string
): string {
  const path = join(scriptDirectory(options), `provider-login-${scriptId(options)}.${extension}`)
  writeFileSync(path, content, { encoding: 'utf8', flag: 'wx', mode: 0o700 })
  if (extension !== 'ps1') chmodSync(path, 0o700)
  return path
}

function windowSpawn(
  options: HostNodeTerminalWindowLauncherOptions
): HostNodeTerminalWindowSpawn | null {
  const platform = options.platform ?? process.platform
  const environment = options.env ?? process.env
  const spawn =
    options.spawn ?? ((executable, args, spawnOptions) => nodeSpawn(executable, args, spawnOptions))
  const linux = platform === 'linux' ? linuxTerminalCommand(options, environment) : null
  if (platform !== 'darwin' && platform !== 'win32' && !linux) return null

  return (executable, args, inheritedOptions) => {
    const removedKeys = removedEnvironmentKeys(environment, inheritedOptions.env)
    let child: ChildProcess
    if (platform === 'darwin') {
      const scriptPath = writeScript(options, 'command', posixScript(executable, args, removedKeys))
      child = spawn(
        options.darwinOpenExecutable ?? '/usr/bin/open',
        ['-a', 'Terminal', scriptPath],
        {
          shell: false,
          stdio: 'ignore'
        }
      )
    } else if (platform === 'win32') {
      const scriptPath = writeScript(
        options,
        'ps1',
        powershellScript(executable, args, removedKeys)
      )
      child = spawn(
        options.windowsPowerShellExecutable ?? 'powershell.exe',
        ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', scriptPath],
        {
          detached: true,
          shell: false,
          stdio: 'ignore',
          windowsHide: false
        }
      )
    } else {
      const scriptPath = writeScript(options, 'sh', posixScript(executable, args, removedKeys))
      child = spawn(linux!.executable, linux!.args(scriptPath), {
        detached: true,
        shell: false,
        stdio: 'ignore'
      })
    }
    child.unref?.()
    return child
  }
}

/** Return undefined on a headless/unsupported platform so auth flows stay honest. */
export function createHostNodeTerminalWindowLauncher(
  options: HostNodeTerminalWindowLauncherOptions = {}
): HostNodeTerminalLauncher | undefined {
  const spawn = windowSpawn(options)
  return spawn ? createHostNodeTerminalLauncher({ spawn }) : undefined
}
