import { join } from 'path'
import { ipcMain } from 'electron'
import { findCatalogInstallCommand } from '../../shared/providerSetupCatalog'

/**
 * "Install" beside "Copy" for the official setup-command catalog (provider CLI
 * installers + Ollama model pulls) in first-launch onboarding and
 * Settings → Providers.
 *
 * SECURITY SHAPE — the renderer sends only a catalog ROW ID; the command is
 * re-resolved HERE from the shared catalog (with the same live-selectable
 * provider filter the render sites apply), so this channel can never execute a
 * renderer-supplied string. The command runs in a visible Terminal window via
 * the same write-a-script-and-openPath mechanism as the provider sign-in and
 * host-tool (gh) lanes — the user watches it run and can abort it; nothing
 * executes hidden inside TaskWraith.
 *
 * Host CLIs (gh) are deliberately NOT routed here: their existing
 * `host-tool:open-install-terminal` lane also upgrades an already-installed
 * copy, which this catalog lane has no business deciding.
 */

export interface InstallCommandTerminalResult {
  ok: boolean
  error?: string
  /** The command that was written to the script, for display/telemetry. */
  command?: string
}

export interface InstallCommandTerminalHandlersDeps {
  getUserDataPath: () => string
  openPath: (path: string) => Promise<string>
  mkdirSync: (path: string, options: { recursive: boolean; mode?: number }) => void
  writeFileSync: (path: string, data: string, options?: { mode?: number }) => void
  chmodSync: (path: string, mode: number) => void
  getPlatform: () => NodeJS.Platform
}

async function openInstallCommandTerminal(
  deps: InstallCommandTerminalHandlersDeps,
  rawId: unknown
): Promise<InstallCommandTerminalResult> {
  try {
    const entry = findCatalogInstallCommand(rawId)
    if (!entry) {
      return { ok: false, error: `Unknown install command: ${String(rawId)}` }
    }
    const platform = deps.getPlatform()
    if (entry.platforms && !entry.platforms.includes(platform)) {
      return {
        ok: false,
        error: `The ${entry.label} installer is not available for this platform.`
      }
    }
    const pulling = entry.kind === 'ollama-model'
    const actionVerb = pulling ? 'Pulling' : 'Installing'
    const actionLabel = pulling ? 'Pull' : 'Install'
    const postscript = pulling
      ? `${actionLabel} finished (exit $status). The model opens a chat — type /bye to leave it, then close this window and return to TaskWraith.`
      : `${actionLabel} finished (exit $status). Close this window and return to TaskWraith.`
    const { command } = entry
    // Model tags carry filename-hostile characters (colons); the row id is
    // catalog-validated above, so sanitizing is about filenames, not safety.
    const fileStem = `install-${entry.id.replace(/[^A-Za-z0-9._-]/g, '-')}`
    const dir = join(deps.getUserDataPath(), 'login')
    deps.mkdirSync(dir, { recursive: true })

    if (platform === 'win32') {
      const psFile = join(dir, `${fileStem}.ps1`)
      const cmdFile = join(dir, `${fileStem}.cmd`)
      const psScript =
        [
          `# Generated by TaskWraith - install ${entry.label}.`,
          '$ErrorActionPreference = "Continue"',
          `Write-Host "${actionVerb} ${entry.label} for TaskWraith..."`,
          `Write-Host "> ${command.replace(/"/g, '`"')}"`,
          'Write-Host ""',
          command,
          '$status = if ($LASTEXITCODE -ne $null) { $LASTEXITCODE } else { 0 }',
          'Write-Host ""',
          `Write-Host "${postscript.replace(/"/g, '`"')}"`
        ].join('\r\n') + '\r\n'
      deps.writeFileSync(psFile, psScript)
      deps.writeFileSync(
        cmdFile,
        `@echo off\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -NoExit -File "%~dp0${fileStem}.ps1"\r\n`
      )
      const err = await deps.openPath(cmdFile)
      if (err) return { ok: false, error: err }
      return { ok: true, command }
    }

    const script =
      [
        '#!/bin/zsh',
        `# Generated by TaskWraith — install ${entry.label}.`,
        // Source the user's shell profile: the app's launchd environment is
        // narrower than their shell's, and npm/brew/ollama frequently only
        // resolve on the shell PATH.
        '[ -f "$HOME/.zprofile" ] && source "$HOME/.zprofile" 2>/dev/null',
        '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc" 2>/dev/null',
        `echo "${actionVerb} ${entry.label} for TaskWraith…"`,
        `echo "> ${command}"`,
        'echo ""',
        command,
        // zsh treats `status` as a read-only alias of `$?`; assigning to it
        // aborts the script, so the POSIX branch captures into `exit_code`.
        'exit_code=$?',
        'echo ""',
        `echo "${postscript.replace('$status', '$exit_code')}"`
      ].join('\n') + '\n'
    const file = join(dir, `${fileStem}.command`)
    deps.writeFileSync(file, script, { mode: 0o755 })
    deps.chmodSync(file, 0o755)
    const err = await deps.openPath(file)
    if (err) return { ok: false, error: err }
    return { ok: true, command }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) }
  }
}

export const INSTALL_COMMAND_TERMINAL_CHANNEL = 'install-command:open-terminal'

export function registerInstallCommandTerminalHandlers(
  deps: InstallCommandTerminalHandlersDeps
): void {
  ipcMain.handle(INSTALL_COMMAND_TERMINAL_CHANNEL, async (_e, commandId: unknown) =>
    openInstallCommandTerminal(deps, commandId)
  )
}
